# Generated by Django 4.2.4 on 2023-08-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular_Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_Title', models.CharField(max_length=200)),
                ('place_Title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
