# Generated by Django 4.2.4 on 2023-08-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_district_packages_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='packages',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='package_Images'),
        ),
        migrations.AddField(
            model_name='packages',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='package_Images'),
        ),
    ]
