# Generated by Django 4.2.4 on 2023-08-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_image_packages_image1_packages_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='package_Images'),
        ),
        migrations.AddField(
            model_name='packages',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='package_Images'),
        ),
    ]
