# Generated by Django 4.2.4 on 2023-08-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_packages_image4_packages_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='place_Title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
