# Generated by Django 4.2.4 on 2023-08-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_packages_place_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='price',
        ),
        migrations.AddField(
            model_name='packages',
            name='budgetPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='luxuryPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='ultimatePrice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
